databases:
  - name: hotwire_ats_postgres
    databaseName: hotwire_ats_production
    plan: free
    ipAllowList: []

services:
  - type: redis
    name: hotwire_ats_redis
    ipAllowList: []
    maxmemoryPolicy: noeviction
    plan: free

  - type: worker
    name: hotwire_ats_sidekiq_worker
    runtime: ruby
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: hotwire_ats_redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  - type: web
    name: hotwire_ats_app
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hotwire_ats_postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: hotwire_ats_redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
